# ---------- Build Stage ----------
FROM python:3.14-slim AS builder

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir --target=/app/deps -r requirements.txt

COPY . .

# ---------- Production Stage ----------    

FROM gcr.io/distroless/python3-debian13

WORKDIR /app

COPY --from=builder  /app /app

ENV PYTHONPATH=/app/deps

CMD ["-m","gunicorn","--bind","0.0.0.0:80","app:app"]