services:
    frontend:
      container_name: chattingo-frontend
      build:
         context: ./frontend
         dockerfile: Dockerfile.multi
      networks: 
       - chattingo
      depends_on:
       - backend
      ports:
       - "80:80"

    backend:
      container_name: chattingo-backend
      build:
         context: ./backend
         dockerfile: Dockerfile.multi
      networks: 
       - chattingo
      environment:
         JWT_SECRET: ${JWT_SECRET}
         SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
         SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
         SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      ports:
       - "8080:8080"
      depends_on:
        mysql:
           condition: service_healthy     


    mysql:
      container_name: mysql 
      image: mysql:5.7 
      networks:
       - chattingo
      ports:
       - "3306:3306"
      volumes:
       - "chat-vol:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
        interval: 10s
        retries: 3
        timeout: 5s
        start_period: 30s
       

networks:
    chattingo:

volumes:
    chat-vol:         