FROM dhi.io/node:24-alpine3.23-dev AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build 

FROM dhi.io/nginx:1-alpine3.23 

WORKDIR /app

COPY  default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder  /app/build /usr/share/nginx/html

CMD ["-g","daemon off;"]