# ---------- Build Stage ----------
FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /app

COPY src/Main.java .
COPY quotes.txt .


RUN javac Main.java 
RUN jar cfe app.jar Main Main.class


# ---------- Production Stage ----------
FROM gcr.io/distroless/java21-debian13

WORKDIR /app

COPY --from=builder /app/app.jar .
COPY --from=builder /app/quotes.txt .

EXPOSE 8000

CMD ["app.jar"]