# ---------- Build Stage ----------
FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /app

COPY /src/Main.java .

COPY quotes.txt .

RUN javac Main.java

# ---------- Production Stage ----------
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=builder /app/Main.class .

COPY --from=builder /app/quotes.txt .

EXPOSE 8000

CMD ["java","Main"]